version: "3.9"

services:
  neo4j:
    image: neo4j:5.26.0
    container_name: neo4j_container
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - ./app/plugins:/plugins
      - ./app/data:/data
      - ./app/logs:/logs
      - ./app/conf:/conf
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "--format", "plain", "RETURN 1"]
      interval: 2s
      timeout: 60s
      retries: 20

  fastapi:
    build:
      context: ./app/src/server
      dockerfile: Dockerfile
    container_name: fastapi_container
    depends_on:
      neo4j:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./app/src/server/models:/app/models/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/health"]
      interval: 2s
      timeout: 2000s
      retries: 1000

  bot:
    build:
      context: ./app/src/bot
      dockerfile: Dockerfile
    container_name: bot_container
    depends_on:
      fastapi:
        condition: service_healthy

  ollama:
    build:
      context: ./app/src/llm/
      dockerfile: Dockerfile
    container_name: ollama_container
    ports:
      - "11434:11434"
    volumes:
      - ./app/src/llm/ollama_data:/root/.ollama
    restart: unless-stopped


volumes:
  ollama_data: