version: "3.9"
services:
  neo4j:
    image: neo4j:5.26.0
    container_name: neo4j_container
    ports:
      - "7474:7474" # HTTP-интерфейс Neo4j
      - "7687:7687" # Bolt-протокол
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - ./plugins:/plugins
      - ./data:/data
      - ./logs:/logs
      - ./conf:/conf
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "--format", "plain", "RETURN 1"]
      interval: 10s
      timeout: 10s
      retries: 5

